#import random module because it will help us generate the Random number in the game 
import random 

#welcoming the User 
print("Welcome to the Number guessing game \nHave Fun :)")

#Asking the user to enter the number range they want for the game the initialization number will always be zero
print("Enter any number  and Test your luck")

#Taking the input from user
user_number=input("Enter your range number : ")

#checking whether the user have entered a digit in the input 
if user_number.isdigit():
    #if its digit then ,converting it into a integer 
    user_number=int(user_number)
    #another IF statement to check if they had entered the number which is below 0 
    if user_number<0:
        print("Please type a number greater than 0 next time")
        quit()#this directly halts the program and quit
        
#if the guess is not a number then asking user to enter numbers next time
else:
    print("please type a number next time.")
    quit()
    
#creating a variable that will store the random number generated by Random Module   

number=random.randint(0,user_number)#in parenthesis we have given the start and end function( end function is our user number which we have asked them at the start)

#making a variable that will keep count of the numbers of try/guesses
Try=0
#creating a loop for user to give them chances until they gets the answer right 
while True: 
    
    Try+=1
    
    #asking the user for the guess
    user_guess=input("make a guess : ")
    
    # checking the input is in digit or not
    if user_guess.isdigit():
        #converting it in int
        user_guess=int(user_guess)
    #if its not a number asking them to type a number next time
    else:
        print("please type a number next time.")
        continue#this skips the rest part of the loop
    
    #start another if else
    if user_guess == number:
        #if they gets the answer right bingo
        print("Bingo")
        #if they get it right no need to loop further we will end the code here
        break
    #if (IF) statement doesn't meets the condition we will come to elif where we will tell the user about their guess which will help them narrow down to guess further
    elif user_guess>number:
            print("Your guess was above the number")
    else:
            print("Your guess is below the number")
#This will tell them the amount of trys it took them for the guess      
print("You got it in",Try,"guesses")   

#Game ends here    
    
        